url: 'https://hamhamwest.com'
domain: hamhamwest
baseurl: ''
title: 'Ham Ham West'
email: apkostka@gmail.com
description: "Ham Ham West is an artist, illustrator, and graphic designer from Seattle, Washington"
keywords: "artist illustrator designer graphic freelance art"
meta_author: Kostka Andrew

defaults:
  - scope:
      path: "assets/img/list-images"
    values:
      list: true

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - pnpm-lock.yaml
  - postcss.config.js
  - tailwind.config.js
  - hamhamwest.com.code-workspace
  - atom-v2.0.0